-- Tabla C.7.1 del Apéndice C: posicion_actual.
-- Decisión del 2026-08-10, cambia el diseño del Apéndice C: en vez de una
-- fila única por procesión sobrescrita con UPSERT, es un HISTÓRICO. Por eso
-- procesion_id es una FK normal (N:1, no UNIQUE ni PK) y la tabla tiene su
-- propio id. Renombrada en plural (posiciones_actuales), como el resto.
--
-- Decisión del 2026-08-11: cada fila es un PING ANÓNIMO (una lectura GPS
-- suelta, sin ligar a ninguna persona ni sesión -no se registra a quién
-- comparte ubicación, ver AuthService/loginConCodigoAcceso). Sin
-- cofrades_activos por fila: la "posición actual" ya no es una fila que se
-- guarda tal cual, se CALCULA leyendo (promedio de los pings de los últimos
-- ~60s, ver PosicionActualService.actual), así que ese dato se cuenta al
-- vuelo, no se persiste.
CREATE TABLE posiciones_actuales (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitud        DOUBLE PRECISION NOT NULL,
    longitud       DOUBLE PRECISION NOT NULL,
    timestamp      TIMESTAMP NOT NULL,
    procesion_id   BIGINT NOT NULL REFERENCES procesiones(id)
);
