-- Tabla C.7.1 del Apéndice C: posicion_actual.
-- Decisión del 2026-08-10, cambia el diseño del Apéndice C: en vez de una
-- fila única por procesión sobrescrita con UPSERT, es un HISTÓRICO de
-- posiciones (cada actualización es un INSERT nuevo). Por eso procesion_id
-- es una FK normal (N:1, no UNIQUE ni PK) y la tabla tiene su propio id.
-- Renombrada en plural (posiciones_actuales), como el resto de tablas.
CREATE TABLE posiciones_actuales (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitud            DOUBLE PRECISION NOT NULL,
    longitud           DOUBLE PRECISION NOT NULL,
    timestamp          TIMESTAMP NOT NULL,
    cofrades_activos   INTEGER,
    procesion_id       BIGINT NOT NULL REFERENCES procesiones(id)
);