-- Tabla intermedia N:M entre recorridos y puntos_ruta (decisión del
-- 2026-08-10: un mismo punto puede formar parte de varios recorridos, con
-- orden/hora_prevista propios de CADA recorrido, no del punto).
--
-- Lleva id propio (no PK compuesta como pasos_procesiones) porque, a
-- diferencia de esa tabla, aquí sí hay columnas propias (orden, hora_prevista)
-- además de las dos FK; un id normal es más simple de manejar en JPA que una
-- clave compuesta, y las dos restricciones UNIQUE de abajo dan las mismas
-- garantías de integridad.
CREATE TABLE recorrido_puntos_ruta (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recorrido_id    BIGINT NOT NULL REFERENCES recorridos(id),
    punto_ruta_id   BIGINT NOT NULL REFERENCES puntos_ruta(id),
    orden           INTEGER NOT NULL,
    hora_prevista   TIMESTAMP,
    UNIQUE (recorrido_id, punto_ruta_id),  -- un punto no se repite dentro del mismo recorrido
    UNIQUE (recorrido_id, orden)           -- dos puntos no pueden compartir posición en el mismo recorrido
);
