-- Tabla C.9 del Apéndice C: usuarios.
-- Decisión del 2026-08-10, cambia el diseño del Apéndice C: raíz de una
-- jerarquía de herencia real (JOINED), como Evento/Procesion y PuntoRuta/
-- PuntoDeInteres. Usuario es abstracta: no tiene sentido un usuario sin rol.
--
-- Solo dos subtipos (V16 MiembroJuntaCofradia, V17 Administrador): el
-- Cofrade dejó de ser un Usuario registrado (decisión del 2026-08-11, no se
-- guarda una fila por persona que comparte ubicación, ver PosicionActual);
-- se autentica con un código de acceso que da un JWT sin crear ningún
-- usuario. Sin columna "rol": con herencia real el tipo lo dice la propia
-- fila (en qué tabla de subtipo tiene pareja).
CREATE TABLE usuarios (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    fecha_ingreso   TIMESTAMP NOT NULL
);
