-- Tabla C.5 del Apéndice C: codigos_acceso.
-- Códigos que emite la cofradía; quien lo valida obtiene un JWT con rol
-- Cofrade, sin que eso cree ninguna fila de usuario (decisión del 2026-08-11:
-- no se registra a las personas que comparten ubicación, ver PosicionActual).
-- El código en sí sigue siendo válido para volver a usarse (no queda "gastado"
-- tras la primera vez), salvo que se revoque.
CREATE TABLE codigos_acceso (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo        VARCHAR(255) NOT NULL UNIQUE,
    estado        VARCHAR(20) NOT NULL DEFAULT 'EMITIDO'
                      CHECK (estado IN ('EMITIDO', 'VALIDADO', 'REVOCADO')),
    cofradia_id   BIGINT NOT NULL REFERENCES cofradias(id)
);
