-- Tabla C.1 del Apéndice C de la memoria: ciudades
CREATE TABLE ciudades (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(255) NOT NULL,
    comunidad_autonoma  VARCHAR(255),
    descripcion         TEXT
);
