-- Tabla C.10 del Apéndice C: notificaciones.
-- Decisión de implementación (2026-08-14, hueco marcado "pendiente" en la
-- memoria): raíz de una jerarquía de herencia real (JOINED), igual que
-- eventos/procesiones y puntos_ruta/puntos_de_interes, en vez de una columna
-- "tipo" ENUM(AVISO/ALERTA) con columnas nullable según el caso como en el
-- Apéndice C. Los subtipos avisos (V21) y alertas (V22) llevan cada uno sus
-- columnas propias. Pendiente actualizar el texto del Apéndice C.
--
-- ciudad_id: hueco no cubierto en el Apéndice C (mismo caso que
-- eventos.ubicacion_id en su momento) -- sin esto el ciudadano no podría
-- filtrar "las notificaciones de mi ciudad", ni la Junta que las crea tendría
-- un ámbito que comprobar (mismo patrón de propiedad que cofradias/pasos/eventos).
CREATE TABLE notificaciones (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo          VARCHAR(255) NOT NULL,
    fecha_creacion  TIMESTAMP NOT NULL,
    ciudad_id       BIGINT NOT NULL REFERENCES ciudades(id)
);
