-- Tabla C.2 del Apéndice C: juntas_cofradias.
-- Relación 1:1 con ciudades: ciudad_id es NOT NULL y UNIQUE, así una ciudad
-- nunca puede tener más de una Junta de Cofradías.
CREATE TABLE juntas_cofradias (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(255) NOT NULL,
    email       VARCHAR(255),
    telefono    VARCHAR(50),
    ciudad_id   BIGINT NOT NULL UNIQUE REFERENCES ciudades(id)
);
