-- Tabla C.3 del Apéndice C: cofradias.
-- Relación 1:N con ciudades: varias cofradías pueden pertenecer a la misma ciudad.
-- NOTA: desviación respecto al Apéndice C tal cual está redactado en el PDF:
-- el campo se llama "web" (URL del sitio propio de la cofradía), no
-- "archivo_informacion" (URL a Firebase Storage). Pendiente de actualizar el
-- texto del Apéndice C y el diagrama de dominio (Figura 3.5) en la memoria.
CREATE TABLE cofradias (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                VARCHAR(255) NOT NULL,
    historia              TEXT,
    web                   VARCHAR(500),
    fecha_creacion        TIMESTAMP,
    ciudad_id             BIGINT NOT NULL REFERENCES ciudades(id)
);
