-- Tabla C.3 del Apéndice C: cofradias.
-- Relación 1:N con ciudades: varias cofradías pueden pertenecer a la misma ciudad.
CREATE TABLE cofradias (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                VARCHAR(255) NOT NULL,
    historia              TEXT,
    archivo_informacion   VARCHAR(500),
    fecha_creacion        TIMESTAMP,
    ciudad_id             BIGINT NOT NULL REFERENCES ciudades(id)
);
