-- Notificaciones push (2026-08-23): un dispositivo (móvil del Ciudadano) se
-- registra con su token de Expo Push contra la ciudad que tiene
-- seleccionada -el Ciudadano nunca se autentica (RI-01), así que no hay
-- usuario al que asociar el token, solo la ciudad cuyas notificaciones le
-- interesan. UNIQUE en token: un mismo dispositivo se reregistra (upsert)
-- si cambia de ciudad o el token se renueva, no se acumulan filas viejas.
CREATE TABLE dispositivos_push (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token               VARCHAR(255) NOT NULL UNIQUE,
    ciudad_id           BIGINT NOT NULL REFERENCES ciudades(id),
    fecha_registro      TIMESTAMP NOT NULL,
    fecha_actualizado   TIMESTAMP NOT NULL
);
