-- Tabla C.4 del Apéndice C: pasos.
-- Relación 1:N con cofradias.
-- historia + analisis_artistico en vez de descripcion: desviación del
-- 2026-08-10, necesidad detectada al construir el front. Pendiente de
-- actualizar el Apéndice C del PDF.
CREATE TABLE pasos (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               VARCHAR(255) NOT NULL,
    historia             TEXT,
    analisis_artistico   TEXT,
    imagen               VARCHAR(500),
    cofradia_id          BIGINT NOT NULL REFERENCES cofradias(id)
);
