-- Tabla nueva, no está en el Apéndice C actual de la memoria (hueco detectado
-- el 2026-08-10: falta en Evento y PuntoRuta). Tabla reutilizable de
-- ubicaciones geográficas, referenciada por eventos y puntos_ruta (y
-- potencialmente por más entidades en el futuro).
CREATE TABLE ubicaciones (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitud     DOUBLE PRECISION NOT NULL,
    longitud    DOUBLE PRECISION NOT NULL,
    direccion   VARCHAR(255)
);
