-- Tabla C.6 del Apéndice C: eventos.
-- Relación con cofradias cambiada de 1:N a N:M el 2026-08-11 (ver
-- eventos_cofradias, V19): un evento/procesión puede tener más de una
-- cofradía participando. Ya no tiene cofradia_id en esta tabla.
--
-- El "ENUM" del Apéndice C se implementa como VARCHAR + CHECK, no como tipo
-- ENUM nativo de PostgreSQL: es más simple de mantener (añadir un valor nuevo
-- es un ALTER TABLE normal, no un ALTER TYPE especial) y encaja igual de bien
-- con @Enumerated(EnumType.STRING) en la entidad JPA.
-- ubicacion_id: hueco detectado el 2026-08-10, no está en el Apéndice C
-- tal cual redactado en el PDF. Pendiente actualizar el texto de la memoria.
-- historia + tradicion en vez de descripcion: desviación del 2026-08-10,
-- necesidad detectada al construir el front. Pendiente de actualizar el
-- Apéndice C del PDF.
CREATE TABLE eventos (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(255) NOT NULL,
    historia       TEXT,
    tradicion      TEXT,
    fecha          TIMESTAMP NOT NULL,
    estado         VARCHAR(20) NOT NULL DEFAULT 'PROGRAMADO'
                       CHECK (estado IN ('PROGRAMADO', 'EN_CURSO', 'FINALIZADO', 'CANCELADO')),
    ubicacion_id   BIGINT NOT NULL REFERENCES ubicaciones(id)
);
