-- Tabla C.8 del Apéndice C: recorridos.
-- No tiene FK propia: es procesiones quien referenciará a recorridos (relación
-- 1:1), no al revés.
CREATE TABLE recorridos (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distancia_total   DOUBLE PRECISION,
    tiempo_estimado   INTEGER
);
