-- Tabla C.8.1 del Apéndice C: puntos_ruta.
-- ubicacion_id en vez de latitud/longitud/direccion propias: hueco detectado
-- el 2026-08-10, no está en el Apéndice C tal cual redactado en el PDF.
--
-- Decisión del 2026-08-10, cambia el diseño del Apéndice C: PuntoRuta es la
-- entidad BASE de una jerarquía de herencia real (igual que Evento/Procesion,
-- estrategia JOINED). Existen puntos "de paso" simples (solo esta tabla, sin
-- nombre/tipo) y puntos "de interés" con detalle (tabla puntos_de_interes,
-- ver V12), que se apoyan en esta misma fila por id.
--
-- Ya NO tiene recorrido_id/hora_prevista/orden: un mismo punto (misma
-- iglesia, misma plaza) puede formar parte de varios recorridos distintos
-- -relación N:M, ver V13 recorrido_puntos_ruta-, y "en qué orden"/"a qué hora"
-- depende de EN QUÉ recorrido esté, no del punto en sí.
CREATE TABLE puntos_ruta (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ubicacion_id   BIGINT NOT NULL REFERENCES ubicaciones(id)
);
