-- Tabla C.8.1 del Apéndice C: puntos_ruta.
-- Relación 1:N con recorridos ("compuesto por" en la Tabla C.15).
-- ubicacion_id en vez de latitud/longitud/direccion propias: hueco detectado
-- el 2026-08-10, no está en el Apéndice C tal cual redactado en el PDF.
-- Valores de tipo actualizados el 2026-08-10 para que coincidan con el enum
-- TipoPuntoInteres del diagrama de dominio (Figura 3.5), necesidad detectada
-- al construir el front.
CREATE TABLE puntos_ruta (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            VARCHAR(20) NOT NULL CHECK (tipo IN
                        ('MONUMENTO', 'IGLESIA', 'ENCUENTRO', 'ORACCION',
                         'ENTRADAPROCESION', 'SALIDAPROCESION', 'UBICACIONEVENTO')),
    ubicacion_id    BIGINT NOT NULL REFERENCES ubicaciones(id),
    hora_prevista   TIMESTAMP,
    orden           INTEGER NOT NULL,
    recorrido_id    BIGINT NOT NULL REFERENCES recorridos(id)
);
